export enum OrderStatus{
    ORDER_PLACED = 'ORDER PLACED',
    ORDER_DISPATCHED = 'ORDER DISPATCHED',
    ORDER_DELIVERED = 'ORDER DELIVERED',
    ORDER_CANCELLED = 'ORDER CANCELLED',
    ORDER_RETURNED = 'ORDER RETURNED'
}